(function(){"use strict";const GRADE_POINTS={"A+":4.0,A:3.7,"B+":3.4,B:3.0,"B-":2.5,"C+":2.0,C:1.5,D:1.0,F:0.0,};function percentageToGradePoint(pct){if(pct>=85)return 4.0;if(pct>=80)return 3.7;if(pct>=75)return 3.4;if(pct>=70)return 3.0;if(pct>=65)return 2.5;if(pct>=60)return 2.0;if(pct>=55)return 1.5;if(pct>=50)return 1.0;return 0.0}
const semestersContainer=document.getElementById("uog-calc-semesters-container",);const resultSection=document.getElementById("uog-calc-result");const actionsContainer=document.getElementById("uog-calc-actions");const addSemesterBtn=document.getElementById("uog-calc-add-semester");const calculateBtn=document.getElementById("uog-calc-calculate");const copyBtn=document.getElementById("uog-calc-copy");const resetBtn=document.getElementById("uog-calc-reset");const gradeFormatSelect=document.getElementById("uog-calc-grade-format");const currentCgpaInput=document.getElementById("uog-calc-current-cgpa");const completedCreditsInput=document.getElementById("uog-calc-completed-credits",);let gradeFormat=gradeFormatSelect?gradeFormatSelect.value:"Letter";let previousGradeFormat=gradeFormat;let semesterCount=0;let resultText="";function createSemester(semData){const semIndex=semesterCount++;const semesterDiv=document.createElement("div");semesterDiv.className="uog-calc-semester";semesterDiv.setAttribute("data-semester-index",String(semIndex));const header=document.createElement("h2");header.textContent=`Semester ${semestersContainer.childElementCount + 1}`;semesterDiv.appendChild(header);const coursesDiv=document.createElement("div");coursesDiv.className="uog-calc-courses";semesterDiv.appendChild(coursesDiv);if(semData&&Array.isArray(semData.courses)&&semData.courses.length>0){semData.courses.forEach((course)=>addCourseRow(coursesDiv,course))}else{addCourseRow(coursesDiv)}
const addCourseBtn=document.createElement("button");addCourseBtn.type="button";addCourseBtn.className="st-general-btn st-main-calculation-btn";addCourseBtn.innerHTML='<i class="fa-solid fa-plus"></i> Add Course';addCourseBtn.addEventListener("click",function(){addCourseRow(coursesDiv);saveState()});semesterDiv.appendChild(addCourseBtn);if(semestersContainer.childElementCount>0){const removeBtn=document.createElement("button");removeBtn.type="button";removeBtn.className="st-general-btn st-main-reset-btn";removeBtn.innerHTML='<i class="fa-solid fa-trash"></i> Remove Semester';removeBtn.addEventListener("click",function(){semestersContainer.removeChild(semesterDiv);updateSemesterHeadings();saveState()});semesterDiv.appendChild(removeBtn);const actionsDiv=document.createElement("div");actionsDiv.className="uog-calc-semester-actions";actionsDiv.appendChild(addCourseBtn);if(semestersContainer.childElementCount>0){actionsDiv.appendChild(removeBtn)}
semesterDiv.appendChild(actionsDiv)}
semestersContainer.appendChild(semesterDiv)}
function updateSemesterHeadings(){const semDivs=semestersContainer.querySelectorAll(".uog-calc-semester");semDivs.forEach((semDiv,idx)=>{const h=semDiv.querySelector("h2");if(h){h.textContent=`Semester ${idx + 1}`}})}
function updateGradeInputs(){showLoadingIndicator();const rows=semestersContainer.querySelectorAll(".uog-calc-course-row");rows.forEach((row)=>{const oldGradeEl=row.querySelector(".uog-calc-course-grade");let prevValue="";if(oldGradeEl){prevValue=oldGradeEl.value}
if(oldGradeEl){oldGradeEl.parentNode.removeChild(oldGradeEl)}
let newGradeEl;if(gradeFormat==="Letter"){newGradeEl=document.createElement("select");newGradeEl.className="st-general-input uog-calc-course-grade";const gradeOptions=["","A+","A","B+","B","B-","C+","C","D","F",];gradeOptions.forEach((gr)=>{const opt=document.createElement("option");opt.value=gr;opt.textContent=gr===""?"Grade":gr;newGradeEl.appendChild(opt)});if(prevValue&&GRADE_POINTS.hasOwnProperty(prevValue)){newGradeEl.value=prevValue}
newGradeEl.addEventListener("change",saveState)}else if(gradeFormat==="Percentage"){newGradeEl=document.createElement("input");newGradeEl.type="number";newGradeEl.min="0";newGradeEl.max="100";newGradeEl.step="0.1";newGradeEl.placeholder="Percentage";newGradeEl.className="st-general-input uog-calc-course-grade";if(prevValue&&!isNaN(prevValue)){const num=parseFloat(prevValue);if(previousGradeFormat==="Point"){newGradeEl.value=(num*25).toFixed(1)}else{newGradeEl.value=prevValue}}
newGradeEl.addEventListener("input",saveState)}else{newGradeEl=document.createElement("input");newGradeEl.type="number";newGradeEl.min="0";newGradeEl.max="4";newGradeEl.step="0.01";newGradeEl.placeholder="Grade Point";newGradeEl.className="st-general-input uog-calc-course-grade";if(prevValue&&!isNaN(prevValue)){const num=parseFloat(prevValue);if(previousGradeFormat==="Percentage"){newGradeEl.value=percentageToGradePoint(num).toFixed(2)}else{newGradeEl.value=prevValue}}
newGradeEl.addEventListener("input",saveState)}
const deleteBtn=row.querySelector(".uog-calc-delete-row");row.insertBefore(newGradeEl,deleteBtn)});setTimeout(()=>{hideLoadingIndicator()},150)}
function addCourseRow(coursesDiv,courseData){const row=document.createElement("div");row.className="uog-calc-course-row";const nameInput=document.createElement("input");nameInput.type="text";nameInput.placeholder="Course name";nameInput.className="st-general-input uog-calc-course-name";if(courseData&&courseData.name){nameInput.value=courseData.name}
nameInput.addEventListener("input",saveState);row.appendChild(nameInput);const creditInput=document.createElement("input");creditInput.type="number";creditInput.min="0.5";creditInput.step="0.5";creditInput.placeholder="Credits";creditInput.className="st-general-input uog-calc-course-credits";if(courseData&&typeof courseData.credits!=="undefined"){creditInput.value=String(courseData.credits)}
creditInput.addEventListener("input",saveState);row.appendChild(creditInput);let gradeEl;if(gradeFormat==="Letter"){gradeEl=document.createElement("select");gradeEl.className="st-general-input uog-calc-course-grade";const gradeOptions=["","A+","A","B+","B","B-","C+","C","D","F",];gradeOptions.forEach((grade)=>{const opt=document.createElement("option");opt.value=grade;opt.textContent=grade===""?"Grade":grade;gradeEl.appendChild(opt)});if(courseData&&courseData.grade){gradeEl.value=courseData.grade}
gradeEl.addEventListener("change",saveState)}else if(gradeFormat==="Percentage"){gradeEl=document.createElement("input");gradeEl.type="number";gradeEl.min="0";gradeEl.max="100";gradeEl.step="0.1";gradeEl.placeholder="Percentage";gradeEl.className="st-general-input uog-calc-course-grade";if(courseData&&courseData.grade){gradeEl.value=courseData.grade}
gradeEl.addEventListener("input",saveState)}else{gradeEl=document.createElement("input");gradeEl.type="number";gradeEl.min="0";gradeEl.max="4";gradeEl.step="0.01";gradeEl.placeholder="Grade Point";gradeEl.className="st-general-input uog-calc-course-grade";if(courseData&&courseData.grade){gradeEl.value=courseData.grade}
gradeEl.addEventListener("input",saveState)}
row.appendChild(gradeEl);const deleteBtn=document.createElement("button");deleteBtn.type="button";deleteBtn.className="uog-calc-delete-row";deleteBtn.innerHTML='<i class="fa-solid fa-trash-can"></i>';deleteBtn.title="Remove course";deleteBtn.addEventListener("click",function(){coursesDiv.removeChild(row);saveState()});row.appendChild(deleteBtn);coursesDiv.appendChild(row)}
function handleAddSemester(){createSemester();saveState()}
function handleCalculate(){const allInputs=semestersContainer.querySelectorAll("input, select");allInputs.forEach((el)=>{el.classList.remove("uog-calc-input-error")});const semesters=[];let totalQuality=0;let totalCredits=0;let hasError=!1;const semDivs=semestersContainer.querySelectorAll(".uog-calc-semester");semDivs.forEach((semDiv,index)=>{const courses=[];let semQuality=0;let semCredits=0;const rows=semDiv.querySelectorAll(".uog-calc-course-row");rows.forEach((row)=>{const nameInput=row.querySelector(".uog-calc-course-name");const creditInput=row.querySelector(".uog-calc-course-credits");const gradeEl=row.querySelector(".uog-calc-course-grade");const name=nameInput.value.trim();const credit=parseFloat(creditInput.value);const gradeValue=gradeEl.value;if(!credit||credit<=0){creditInput.classList.add("uog-calc-input-error");hasError=!0;return}
let gradePoint;if(gradeFormat==="Letter"){if(!gradeValue){gradeEl.classList.add("uog-calc-input-error");hasError=!0;return}
gradePoint=GRADE_POINTS[gradeValue]??0}else if(gradeFormat==="Percentage"){const pct=parseFloat(gradeValue);if(isNaN(pct)||pct<0||pct>100){gradeEl.classList.add("uog-calc-input-error");hasError=!0;return}
gradePoint=percentageToGradePoint(pct)}else{const pointVal=parseFloat(gradeValue);if(isNaN(pointVal)||pointVal<0||pointVal>4){gradeEl.classList.add("uog-calc-input-error");hasError=!0;return}
gradePoint=pointVal}
const qualityPoints=gradePoint*credit;semQuality+=qualityPoints;semCredits+=credit;courses.push({name,credits:credit,grade:gradeValue,gradePoint,qualityPoints,})});let semesterGPA=0;if(!hasError&&semCredits>0){semesterGPA=semQuality/semCredits;totalQuality+=semQuality;totalCredits+=semCredits}
semesters.push({index:index+1,courses,totalCredits:semCredits,qualityPoints:semQuality,gpa:semesterGPA,})});if(hasError){alert("Please complete all required fields (credit hours and grade) before calculating.",);return}
if(!hasError){const prevCgpaStr=currentCgpaInput?currentCgpaInput.value.trim():"";const prevCreditsStr=completedCreditsInput?completedCreditsInput.value.trim():"";if(prevCgpaStr!==""||prevCreditsStr!==""){const prevCgpa=parseFloat(prevCgpaStr);const prevCredits=parseFloat(prevCreditsStr);if(isNaN(prevCgpa)||prevCgpa<0||prevCgpa>4||isNaN(prevCredits)||prevCredits<=0){if(currentCgpaInput)
currentCgpaInput.classList.add("uog-calc-input-error");if(completedCreditsInput)
completedCreditsInput.classList.add("uog-calc-input-error");alert("Please provide valid current CGPA (0-4) and completed credits (>0) or leave both blank.",);return}
totalQuality+=prevCgpa*prevCredits;totalCredits+=prevCredits}}
let cgpa=0;if(totalCredits>0){cgpa=totalQuality/totalCredits}
buildResultDisplay(semesters,totalCredits,totalQuality,cgpa);saveState()}
function buildResultDisplay(semesters,totalCredits,totalQuality,cgpa){resultSection.innerHTML="";resultText="";semesters.forEach((sem)=>{const semTitle=document.createElement("div");semTitle.className="uog-calc-semester-title";semTitle.textContent=`Semester ${sem.index}`;resultSection.appendChild(semTitle);resultText+=`Semester ${sem.index}\n`;const table=document.createElement("table");const thead=document.createElement("thead");let gradeLabel;if(gradeFormat==="Letter"){gradeLabel="Grade"}else if(gradeFormat==="Percentage"){gradeLabel="Percentage"}else{gradeLabel="Grade Point (Input)"}
thead.innerHTML=`<tr><th>Course</th><th>Credits</th><th>${gradeLabel}</th><th>Grade Point</th><th>Quality Points</th></tr>`;table.appendChild(thead);const tbody=document.createElement("tbody");sem.courses.forEach((course)=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${course.name || "-"}</td><td>${course.credits}</td><td>${course.grade}</td><td>${course.gradePoint.toFixed(
          2,
        )}</td><td>${course.qualityPoints.toFixed(2)}</td>`;tbody.appendChild(tr);resultText+=`  ${course.name || "-"} — Credits: ${course.credits}, Grade: ${course.grade}, Grade Point: ${course.gradePoint.toFixed(
          2,
        )}, Quality Points: ${course.qualityPoints.toFixed(2)}\n`});table.appendChild(tbody);const summary=document.createElement("div");summary.className="uog-calc-semester-summary";const semGPA=sem.gpa.toFixed(2);summary.innerHTML=`<strong>Total Credits:</strong> ${sem.totalCredits.toFixed(
        2,
      )} &nbsp; <strong>Semester GPA:</strong> ${semGPA}`;table.appendChild(document.createElement("tfoot"));resultSection.appendChild(table);resultSection.appendChild(summary);resultText+=`  Semester credits: ${sem.totalCredits.toFixed(2)}, Semester GPA: ${semGPA}\n\n`});const overallSummary=document.createElement("div");overallSummary.className="uog-calc-overall-summary";const cgpaRounded=cgpa.toFixed(2);overallSummary.innerHTML=`<strong>Cumulative Credits:</strong> ${totalCredits.toFixed(
      2,
    )} &nbsp; <strong>Total Quality Points:</strong> ${totalQuality.toFixed(
      2,
    )} &nbsp; <strong>CGPA:</strong> ${cgpaRounded}`;resultSection.appendChild(overallSummary);resultText+=`Cumulative credits: ${totalCredits.toFixed(2)}, Total quality points: ${totalQuality.toFixed(
      2,
    )}, CGPA: ${cgpaRounded}\n`;const note=document.createElement("div");note.className="uog-calc-note";let warnings="";if(cgpa<2.0){warnings+="Your CGPA is below 2.00, which is the minimum required for BS and 2‑year master’s degrees. "}
if(cgpa<2.5){warnings+="For M.Phil programmes, a minimum CGPA of 2.50 is required."}
if(warnings){note.textContent=warnings}else{note.textContent="Minimum CGPA for BS/Master degrees is 2.00; for M.Phil programmes it is 2.50."}
resultSection.appendChild(note);resultText+=`${note.textContent}\n`;resultSection.classList.remove("uog-calc-hidden");actionsContainer.classList.remove("uog-calc-hidden")}
function saveState(){try{const semData=[];const semDivs=semestersContainer.querySelectorAll(".uog-calc-semester");semDivs.forEach((semDiv)=>{const courses=[];const courseRows=semDiv.querySelectorAll(".uog-calc-course-row");courseRows.forEach((row)=>{const name=row.querySelector(".uog-calc-course-name").value.trim();const creditVal=row.querySelector(".uog-calc-course-credits").value;const credits=creditVal?parseFloat(creditVal):"";const grade=row.querySelector(".uog-calc-course-grade").value;courses.push({name,credits,grade})});semData.push({courses})});const stored={semesters:semData,gradeFormat,currentCgpa:currentCgpaInput?currentCgpaInput.value:"",completedCredits:completedCreditsInput?completedCreditsInput.value:"",resultHTML:resultSection.innerHTML,resultText,resultVisible:!resultSection.classList.contains("uog-calc-hidden"),};sessionStorage.setItem("uogCalcData",JSON.stringify(stored))}catch(e){console.warn("Failed to save state:",e)}}
function restoreState(){try{const dataStr=sessionStorage.getItem("uogCalcData");if(!dataStr){return}
const data=JSON.parse(dataStr);if(!data.semesters||!Array.isArray(data.semesters)){return}
if(data.gradeFormat&&gradeFormatSelect){gradeFormatSelect.value=data.gradeFormat;gradeFormat=data.gradeFormat}
if(currentCgpaInput&&typeof data.currentCgpa!=="undefined"){currentCgpaInput.value=data.currentCgpa}
if(completedCreditsInput&&typeof data.completedCredits!=="undefined"){completedCreditsInput.value=data.completedCredits}
semestersContainer.innerHTML="";semesterCount=0;data.semesters.forEach((sem)=>{createSemester(sem)});updateSemesterHeadings();updateGradeInputs();if(data.resultVisible&&data.resultHTML){resultSection.innerHTML=data.resultHTML;resultSection.classList.remove("uog-calc-hidden");actionsContainer.classList.remove("uog-calc-hidden");resultText=data.resultText||""}}catch(e){console.warn("Failed to restore state:",e)}}
function handleCopy(){if(!resultText){alert("Please calculate results before copying.");return}
if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(resultText).then(()=>{alert("Result copied to clipboard.")}).catch((err)=>{console.error("Clipboard copy failed",err);alert("Failed to copy results.")})}else{const textarea=document.createElement("textarea");textarea.value=resultText;document.body.appendChild(textarea);textarea.select();try{document.execCommand("copy");alert("Result copied to clipboard.")}catch(err){alert("Failed to copy results.")}
document.body.removeChild(textarea)}}
function handleReset(){if(!confirm("Are you sure you want to reset everything?")){return}
sessionStorage.removeItem("uogCalcData");semestersContainer.innerHTML="";semesterCount=0;resultSection.innerHTML="";resultText="";resultSection.classList.add("uog-calc-hidden");actionsContainer.classList.add("uog-calc-hidden");if(gradeFormatSelect){gradeFormatSelect.value="Letter";gradeFormat="Letter"}
if(currentCgpaInput)currentCgpaInput.value="";if(completedCreditsInput)completedCreditsInput.value="";createSemester()}
addSemesterBtn.addEventListener("click",handleAddSemester);calculateBtn.addEventListener("click",handleCalculate);copyBtn.addEventListener("click",handleCopy);resetBtn.addEventListener("click",handleReset);if(gradeFormatSelect){gradeFormatSelect.addEventListener("change",function(){previousGradeFormat=gradeFormat;gradeFormat=gradeFormatSelect.value;updateGradeInputs();saveState()})}
function showLoadingIndicator(){const overlay=document.getElementById("uog-calc-loading");if(overlay){overlay.classList.remove("uog-calc-hidden")}}
function hideLoadingIndicator(){const overlay=document.getElementById("uog-calc-loading");if(overlay){overlay.classList.add("uog-calc-hidden")}}
function runTests(){const testCases=[{id:"TestCase1",courses:[{grade:"A+",credits:3},{grade:"B",credits:3},],expected:3.5,},{id:"TestCase2",courses:[{grade:"A+",credits:3},{grade:"B",credits:3},{grade:"A",credits:2},{grade:"C",credits:4},],expected:2.8667,},{id:"TestCase3",courses:[{grade:"B+",credits:3},{grade:"C+",credits:4},{grade:"D",credits:3},{grade:"F",credits:3},],expected:1.6308,},];console.log("Running GPA calculation tests...");testCases.forEach((t)=>{let totalQP=0;let totalCr=0;t.courses.forEach((c)=>{const gp=GRADE_POINTS[c.grade];totalQP+=gp*c.credits;totalCr+=c.credits});const gpa=totalQP/totalCr;const pass=Math.abs(gpa-t.expected)<0.0001;console.log(`${t.id}: calculated=${gpa.toFixed(4)}, expected=${t.expected}, pass=${pass}`,)})}
if(currentCgpaInput){currentCgpaInput.addEventListener("input",saveState)}
if(completedCreditsInput){completedCreditsInput.addEventListener("input",saveState)}
restoreState();if(semestersContainer.childElementCount===0){createSemester()}})()
